import React, { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Header from "@/components/layouts/Header";
import Menu from "@/components/layouts/Menu";
import "./globals.css";
const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rostik 1488",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable} antialiased container mx-auto px-10`}>
        <Providers>
          <Header>
            <Menu />
          </Header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
